<a href="https://colab.research.google.com/github/liuxiaomiao123/HDDM/blob/master/Python_Workshop_Pre1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1 Python Fundamentals

In [ ]:
from google.colab import files
files.upload()

In [ ]:
x=34.4;
print("x=",x);

2 How can I process tabular data files in Python?

In [ ]:
#-----------------------------------Uploading data---------------------------------------------------------------
import numpy as np
data = np.loadtxt(fname='inflammation-01.csv', delimiter=',');  

# np.loadtxt has two parameters: the name of the file we want to read and the delimiter that separates values on a line
# to save space when displaying NumPy arrays, Python does not show us trailing zeros, so 1.0 becomes 1.

print(data)   # add ; to hide the display

print(type(data))   # a variable is a Numpy array

print(data.dtype)  # the type of the data contained in the NumPy array.

print(data.shape)  # rows,columns


In [ ]:
#----------------------------------Slicing data----------------------------------------------------

print('first value in data:',data[0,0])   # Languages in the C family (including C++, Java, Perl, and Python) count from 0 because it represents an offset from the first value in the array (the second value is offset by one index from the first value). 

print(data[0:4, 0:10])  # The slice 0:4 means, “Start at index 0 and go up to, but not including, index 4”. Again, the up-to-but-not-including takes a bit of getting used to, but the rule is that the difference between the upper and lower bounds is the number of values in the slice.

print(data[:3,6:])    #  We also don’t have to include the upper and lower bound on the slice. 
                      # If we don’t include the lower bound, Python uses 0 by default; 
                      # if we don’t include the upper, the slice runs to the end of the axis
                      # if we don’t include either (i.e., if we use ‘:’ on its own), the slice includes everything:

In [ ]:
#----------------------------------Analyzing data----------------------------------------------------

vmax, vimn, vmean, vstd = np.max(data), np.min(data), np.mean(data), np.std(data);
print(vmax, vimn, vmean, vstd);

print(numpy.mean(data, axis=0));   # vertical
print(numpy.mean(data, axis=0).shape);  # The expression (40,) tells us we have an N×1 vector
print(numpy.mean(data, axis=1));   # horizontal

In [ ]:
#---------------------------------Slicing string-------------------------------------------------------

element = 'oxygen';
print(element[:4]);   # oxyg

print(element[-1]);   # n 
print(element[-2]);   # e 

print(element[1:-1]);  # Creates a substring from index 1 up to (not including) the final index, effectively removing the first and last letters from ‘oxygen’

print(element[3:3]);   # empty string

In [34]:
#---------------------------------Stacking arrays--------------------------------------------------------

A = np.array([[1,2,3],[4,5,6]])
print(A)

B = numpy.hstack([A, A])
print(B)

C = numpy.vstack([A, A])
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [ ]:
#----------------------------------Key points--------------------------------------------------------------

Import a library into a program using import libraryname.

Use the numpy library to work with arrays in Python.

The expression array.shape gives the shape of an array.

Use array[x, y] to select a single element from a 2D array.

Array indices start at 0, not 1.

Use low:high to specify a slice that includes the indices from low to high-1.

Use # some kind of explanation to add comments to programs.

Use numpy.mean(array), numpy.max(array), and numpy.min(array) to calculate simple statistics.

Use numpy.mean(array, axis=0) or numpy.mean(array, axis=1) to calculate statistics across the specified axis.